# Generated by Django 4.1.2 on 2022-10-26 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cohort', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=32)),
                ('unit', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('followup', 'Follow Up'), ('resolved', 'Resolved')], default='followup', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.student')),
            ],
        ),
    ]
